### ISSUE TITLE
satellite update?

### ISSUE THREAD

**Issue by dirteat** [jmozmoz/cloudmap#10]
Hi there,
there is some weird output map from GEOS_15_4_S1, it looks as if the projection is a mollweide one and that seems to screw the final cloud_map.

I've done a check on the Dundee website, there are new satellite there from japan and india, maybe we could be used as a replacement?

Thanks,
Cheers.

**Comment by jmozmoz** [comment]
I looks like this is a fallout of the government shutdown in the US:
https://www.goes-r.gov/multimedia/dataAndImageryImages.html

If you temporarily remove the GEOS15 part from the satellites.json file (in $HOME/.CreateCloadMap) most of the map is shown correctly.

**Comment by krkeegan** [comment]
This isn't shutdown related.  The Dundee website lists the satellite as being inactive since 8 Nov 2018, well before the shutdown.  

The wikipedia page also says it is being retired, it started its move out of the 135W position around November 8.  In theory there is supposed to be a six month overlap, but maybe Dundee decided just to the replacement GOES 17 was sufficient?  Either way, GOES 17 is working and seems to be providing similar images to replace it.

https://en.wikipedia.org/wiki/GOES_15.

**Comment by krkeegan** [comment]
Oh, nope apologies, now I think I have it all figured out.

GOES 15 was moved around November 8 to make room for GOES 17.  GOES 15 is now at 128W rather than 135W and Dundee has updated its links to reflect that.  Here is a recent GOES 15 link:

http://www.sat.dundee.ac.uk/xrit/128.0W/GOES/2019/1/15/1500/2019_1_15_1500_GOES15_4_S4.jpeg

So at somepoint in the approximate next 6 months GOES 15 will go offline.  But in the interim it just has a new position and url.

**Comment by krkeegan** [comment]
Apologies, it looks like you all fixed this already.  Please ignore me. :blush:

**Comment by krkeegan** [comment]
It looks like the resolution of GOES15 was decreased slightly, this resulted in our crop numbers actually adding blank space to the image.  The PR fixes the issue for me.  Apologies again for posting irrelevant information.
